import type { DesktopModelSettings } from "./contracts"

/** Fresh model-settings state for one isolated in-memory Desktop Bridge. */
export function createMemoryModelSettings(): DesktopModelSettings {
  return {
    provider: "custom",
    model: "gpt-5.4",
    apiBaseUrl: "https://api.openai.com/v1",
    apiKey: "",
    apiKeyConfigured: false,
    maxConcurrentModelCalls: 1,
    requestsPerMinute: null,
    tokensPerMinute: null,
    analysisModel: null,
    answerModel: null,
    defaultContextCapacity: null,
    analysisContextCapacity: null,
    answerContextCapacity: null,
    defaultReasoning: null,
    analysisReasoning: null,
    answerReasoning: null,
    defaultInputPricePerMillion: null,
    defaultOutputPricePerMillion: null,
    analysisInputPricePerMillion: null,
    analysisOutputPricePerMillion: null,
    answerInputPricePerMillion: null,
    answerOutputPricePerMillion: null,
    analysisConcurrency: 1,
    providerAdapter: {
      identity: "custom",
      version: "custom.compatibility.v1",
      structuredOutputMode: null,
      supportsStructuredAnalysis: false,
      supportedReasoning: [],
      analysisUnavailableReason: "Custom providers do not have a code-owned structured Analysis protocol.",
    },
    effectiveRoles: {
      default: { model: "gpt-5.4", contextCapacity: 128000, reasoning: null, reasoningSource: "provider_default" },
      analysis: { model: "gpt-5.4", contextCapacity: 128000, reasoning: "off", reasoningSource: "analysis_safe_default" },
      answer: { model: "gpt-5.4", contextCapacity: 128000, reasoning: null, reasoningSource: "provider_default" },
    },
    analysisCapability: {
      profileIdentity: null,
      status: "unchecked",
      failureCode: "analysis_profile_unavailable",
      reason: "Custom providers do not have a code-owned structured Analysis protocol.",
      checkedAt: null,
    },
    answerCapability: {
      profileIdentity: null,
      status: "unchecked",
      failureCode: null,
      reason: null,
      checkedAt: null,
    },
    usageAggregate: {
      callCount: 0,
      attemptCount: 0,
      failureCount: 0,
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      totalCost: null,
      tokenUsageSource: null,
    },
  }
}
