"""Ordered feature migrations layered after the Desktop workspace core schema."""

from openkb import desktop_knowledge_lifecycle_migrations as lifecycle_migrations
from openkb import desktop_knowledge_page_migrations as knowledge_page_migrations
from openkb import desktop_knowledge_reanalysis_migrations as reanalysis_migrations
from openkb import desktop_knowledge_verification_migrations as verification_migrations
from openkb import desktop_page_tree_migrations as page_tree_migrations
from openkb.desktop_candidate_registry_migrations import (
    CANDIDATE_REGISTRY_MIGRATION_STATEMENTS,
)
from openkb.desktop_catalog_migrations import (
    CATALOG_ELIGIBILITY_MIGRATION_STATEMENTS,
    CATALOG_MIGRATION_STATEMENTS,
)
from openkb.desktop_corpus_benchmark_migrations import CORPUS_BENCHMARK_MIGRATION_STATEMENTS
from openkb.desktop_corpus_knowledge_migrations import CORPUS_KNOWLEDGE_MIGRATION_STATEMENTS
from openkb.desktop_corpus_synthesis_task_migrations import (
    CORPUS_SYNTHESIS_TASK_MIGRATION_STATEMENTS,
)
from openkb.desktop_document_version_catalog_migrations import (
    DOCUMENT_VERSION_CATALOG_MIGRATION_STATEMENTS,
)
from openkb.desktop_inventory_identity_binding_migrations import (
    INVENTORY_IDENTITY_BINDING_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_adoption_migrations import (
    KNOWLEDGE_ADOPTION_MIGRATION_STATEMENTS,
    KNOWLEDGE_ADOPTION_REQUEST_INPUT_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_analysis_batch_migrations import (
    KNOWLEDGE_ANALYSIS_BATCH_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_analysis_migrations import (
    KNOWLEDGE_ANALYSIS_METADATA_MIGRATION_STATEMENTS,
    KNOWLEDGE_ANALYSIS_MIGRATION_STATEMENTS,
    KNOWLEDGE_ANALYSIS_PROVENANCE_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_analysis_plan_migrations import (
    KNOWLEDGE_ANALYSIS_PLAN_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_graph_interpretation_migrations import (
    KNOWLEDGE_GRAPH_INTERPRETATION_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_graph_result_migrations import (
    KNOWLEDGE_GRAPH_CURRENT_REVISION_MIGRATION_STATEMENTS,
    KNOWLEDGE_GRAPH_RESULT_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_graph_task_migrations import (
    KNOWLEDGE_GRAPH_RETRY_SCOPE_MIGRATION_STATEMENTS,
    KNOWLEDGE_GRAPH_TASK_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_link_migrations import (
    CATALOG_RELATIONSHIP_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_provenance_migrations import (
    KNOWLEDGE_PROVENANCE_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_reconciliation_migrations import (
    THREE_WAY_KNOWLEDGE_RECONCILIATION_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_relationship_migrations import (
    KNOWLEDGE_RELATIONSHIP_MIGRATION_STATEMENTS,
)
from openkb.desktop_knowledge_source_migrations import KNOWLEDGE_SOURCE_MIGRATION_STATEMENTS
from openkb.desktop_legacy_model_recovery_migrations import (
    LEGACY_MODEL_RECOVERY_MIGRATION_STATEMENTS,
)
from openkb.desktop_missing_source_migrations import MISSING_SOURCE_MIGRATION_STATEMENTS
from openkb.desktop_model_capability_migrations import MODEL_CAPABILITY_MIGRATION_STATEMENTS
from openkb.desktop_model_observability_migrations import MODEL_LIFECYCLE_MIGRATION_STATEMENTS
from openkb.desktop_model_operation_migrations import (
    MODEL_OPERATION_AUDIT_MIGRATION_STATEMENTS,
    MODEL_OPERATION_RETRY_MIGRATION_STATEMENTS,
    MODEL_OPERATION_RETRY_REVISION_MIGRATION_STATEMENTS,
    MODEL_OPERATION_STATE_MIGRATION_STATEMENTS,
)
from openkb.desktop_model_result_migrations import (
    MODEL_RESULT_OBSERVATION_MIGRATION_STATEMENTS,
)
from openkb.desktop_model_usage_migrations import MODEL_USAGE_MIGRATION_STATEMENTS
from openkb.desktop_okf_projection_migrations import OKF_PROJECTION_MIGRATION_STATEMENTS
from openkb.desktop_page_tree_enrichment_migrations import (
    PAGE_TREE_ENRICHMENT_MIGRATION_STATEMENTS,
    PAGE_TREE_ENRICHMENT_RETRY_SCOPE_MIGRATION_STATEMENTS,
)
from openkb.desktop_retrieval_trace_migrations import RETRIEVAL_TRACE_MIGRATION_STATEMENTS
from openkb.desktop_semantic_graph_binding_migrations import (
    SEMANTIC_GRAPH_RESULT_BINDING_MIGRATION_STATEMENTS,
)
from openkb.desktop_semantic_graph_migrations import SEMANTIC_GRAPH_MIGRATION_STATEMENTS
from openkb.desktop_workspace_migrations import (
    CONVERSATION_MIGRATION_STATEMENTS,
    DEDUPLICATION_MIGRATION_STATEMENTS,
    DOCUMENT_VERSION_CANDIDATE_MIGRATION_STATEMENTS,
    GRAPH_FEATURE_FLAG_MIGRATION_STATEMENTS,
    GROUNDED_ANSWER_MIGRATION_STATEMENTS,
    GROUNDED_ANSWER_SOURCE_IMAGE_MIGRATION_STATEMENTS,
    INTERRUPTED_ANSWER_MIGRATION_STATEMENTS,
    KNOWLEDGE_GRAPH_MIGRATION_STATEMENTS,
    KNOWLEDGE_PAGE_MIGRATION_STATEMENTS,
    KNOWLEDGE_RECONCILIATION_MIGRATION_STATEMENTS,
    KNOWLEDGE_RECONCILIATION_RESOLUTION_MIGRATION_STATEMENTS,
    MODEL_CALL_MIGRATION_STATEMENTS,
    RAW_ASSET_INTEGRITY_MIGRATION_STATEMENTS,
    RECOVERY_RUN_MIGRATION_STATEMENTS,
    SOURCE_IMAGE_MIGRATION_STATEMENTS,
)

KNOWLEDGE_ANALYSIS_MIGRATION_VERSION = 26
MODEL_LIFECYCLE_MIGRATION_VERSION = 38
KNOWLEDGE_ANALYSIS_PLAN_MIGRATION_VERSION = 39
MODEL_USAGE_MIGRATION_VERSION = 40
LEGACY_MODEL_RECOVERY_MIGRATION_VERSION = 41
KNOWLEDGE_GRAPH_TASK_MIGRATION_VERSION = 42
MODEL_RESULT_OBSERVATION_MIGRATION_VERSION = 43
MODEL_CAPABILITY_MIGRATION_VERSION = 44
MODEL_OPERATION_STATE_MIGRATION_VERSION = 45
KNOWLEDGE_ADOPTION_MIGRATION_VERSION = 46
KNOWLEDGE_GRAPH_RESULT_MIGRATION_VERSION = 47
MODEL_OPERATION_RETRY_MIGRATION_VERSION = 48
KNOWLEDGE_ADOPTION_REQUEST_INPUT_MIGRATION_VERSION = 49
MODEL_OPERATION_AUDIT_MIGRATION_VERSION = 50
KNOWLEDGE_GRAPH_CURRENT_REVISION_MIGRATION_VERSION = 51
KNOWLEDGE_GRAPH_INTERPRETATION_MIGRATION_VERSION = 52
CORPUS_KNOWLEDGE_MIGRATION_VERSION = 53
CORPUS_BENCHMARK_MIGRATION_VERSION = 54
CATALOG_RELATIONSHIP_MIGRATION_VERSION = 55
KNOWLEDGE_RELATIONSHIP_MIGRATION_VERSION = 56
CATALOG_ELIGIBILITY_MIGRATION_VERSION = 57
SEMANTIC_GRAPH_MIGRATION_VERSION = 58
CANDIDATE_REGISTRY_MIGRATION_VERSION = 59
DOCUMENT_VERSION_CATALOG_MIGRATION_VERSION = 60
SEMANTIC_GRAPH_RESULT_BINDING_MIGRATION_VERSION = 61
CORPUS_SYNTHESIS_TASK_MIGRATION_VERSION = 62
INVENTORY_IDENTITY_BINDING_MIGRATION_VERSION = 63


DESKTOP_FEATURE_MIGRATIONS: tuple[tuple[int, tuple[str, ...]], ...] = (
    (4, MODEL_CALL_MIGRATION_STATEMENTS),
    (5, RECOVERY_RUN_MIGRATION_STATEMENTS),
    (6, RAW_ASSET_INTEGRITY_MIGRATION_STATEMENTS),
    (7, SOURCE_IMAGE_MIGRATION_STATEMENTS),
    (8, GROUNDED_ANSWER_MIGRATION_STATEMENTS),
    (9, GROUNDED_ANSWER_SOURCE_IMAGE_MIGRATION_STATEMENTS),
    (10, INTERRUPTED_ANSWER_MIGRATION_STATEMENTS),
    (11, KNOWLEDGE_PAGE_MIGRATION_STATEMENTS),
    (12, DEDUPLICATION_MIGRATION_STATEMENTS),
    (13, DOCUMENT_VERSION_CANDIDATE_MIGRATION_STATEMENTS),
    (14, KNOWLEDGE_RECONCILIATION_MIGRATION_STATEMENTS),
    (15, KNOWLEDGE_RECONCILIATION_RESOLUTION_MIGRATION_STATEMENTS),
    (16, KNOWLEDGE_GRAPH_MIGRATION_STATEMENTS),
    (17, GRAPH_FEATURE_FLAG_MIGRATION_STATEMENTS),
    (18, CONVERSATION_MIGRATION_STATEMENTS),
    (19, knowledge_page_migrations.KNOWLEDGE_PAGE_DRAFT_MIGRATION_STATEMENTS),
    (20, KNOWLEDGE_SOURCE_MIGRATION_STATEMENTS),
    (21, KNOWLEDGE_PROVENANCE_MIGRATION_STATEMENTS),
    (22, verification_migrations.KNOWLEDGE_VERIFICATION_MIGRATION_STATEMENTS),
    (23, lifecycle_migrations.KNOWLEDGE_LIFECYCLE_MIGRATION_STATEMENTS),
    (24, THREE_WAY_KNOWLEDGE_RECONCILIATION_MIGRATION_STATEMENTS),
    (25, OKF_PROJECTION_MIGRATION_STATEMENTS),
    (KNOWLEDGE_ANALYSIS_MIGRATION_VERSION, KNOWLEDGE_ANALYSIS_MIGRATION_STATEMENTS),
    (27, KNOWLEDGE_ANALYSIS_PROVENANCE_MIGRATION_STATEMENTS),
    (28, KNOWLEDGE_ANALYSIS_METADATA_MIGRATION_STATEMENTS),
    (29, MISSING_SOURCE_MIGRATION_STATEMENTS),
    (30, KNOWLEDGE_ANALYSIS_BATCH_MIGRATION_STATEMENTS),
    (31, reanalysis_migrations.KNOWLEDGE_REANALYSIS_MIGRATION_STATEMENTS),
    (32, page_tree_migrations.PAGE_TREE_MIGRATION_STATEMENTS),
    (33, page_tree_migrations.PAGE_TREE_LIFECYCLE_MIGRATION_STATEMENTS),
    (34, PAGE_TREE_ENRICHMENT_MIGRATION_STATEMENTS),
    (35, CATALOG_MIGRATION_STATEMENTS),
    (36, RETRIEVAL_TRACE_MIGRATION_STATEMENTS),
    (37, page_tree_migrations.PAGE_TREE_PROVIDER_EVALUATION_MIGRATION_STATEMENTS),
    (MODEL_LIFECYCLE_MIGRATION_VERSION, MODEL_LIFECYCLE_MIGRATION_STATEMENTS),
    (KNOWLEDGE_ANALYSIS_PLAN_MIGRATION_VERSION, KNOWLEDGE_ANALYSIS_PLAN_MIGRATION_STATEMENTS),
    (MODEL_USAGE_MIGRATION_VERSION, MODEL_USAGE_MIGRATION_STATEMENTS),
    (LEGACY_MODEL_RECOVERY_MIGRATION_VERSION, LEGACY_MODEL_RECOVERY_MIGRATION_STATEMENTS),
    (KNOWLEDGE_GRAPH_TASK_MIGRATION_VERSION, KNOWLEDGE_GRAPH_TASK_MIGRATION_STATEMENTS),
    (
        MODEL_RESULT_OBSERVATION_MIGRATION_VERSION,
        MODEL_RESULT_OBSERVATION_MIGRATION_STATEMENTS,
    ),
    (MODEL_CAPABILITY_MIGRATION_VERSION, MODEL_CAPABILITY_MIGRATION_STATEMENTS),
    (MODEL_OPERATION_STATE_MIGRATION_VERSION, MODEL_OPERATION_STATE_MIGRATION_STATEMENTS),
    (KNOWLEDGE_ADOPTION_MIGRATION_VERSION, KNOWLEDGE_ADOPTION_MIGRATION_STATEMENTS),
    (KNOWLEDGE_GRAPH_RESULT_MIGRATION_VERSION, KNOWLEDGE_GRAPH_RESULT_MIGRATION_STATEMENTS),
    (MODEL_OPERATION_RETRY_MIGRATION_VERSION, MODEL_OPERATION_RETRY_MIGRATION_STATEMENTS),
    (
        KNOWLEDGE_ADOPTION_REQUEST_INPUT_MIGRATION_VERSION,
        KNOWLEDGE_ADOPTION_REQUEST_INPUT_MIGRATION_STATEMENTS,
    ),
    (MODEL_OPERATION_AUDIT_MIGRATION_VERSION, MODEL_OPERATION_AUDIT_MIGRATION_STATEMENTS),
    (
        KNOWLEDGE_GRAPH_CURRENT_REVISION_MIGRATION_VERSION,
        KNOWLEDGE_GRAPH_CURRENT_REVISION_MIGRATION_STATEMENTS,
    ),
    (
        KNOWLEDGE_GRAPH_INTERPRETATION_MIGRATION_VERSION,
        KNOWLEDGE_GRAPH_INTERPRETATION_MIGRATION_STATEMENTS
        + MODEL_OPERATION_RETRY_REVISION_MIGRATION_STATEMENTS
        + KNOWLEDGE_GRAPH_RETRY_SCOPE_MIGRATION_STATEMENTS
        + PAGE_TREE_ENRICHMENT_RETRY_SCOPE_MIGRATION_STATEMENTS,
    ),
    (CORPUS_KNOWLEDGE_MIGRATION_VERSION, CORPUS_KNOWLEDGE_MIGRATION_STATEMENTS),
    (CORPUS_BENCHMARK_MIGRATION_VERSION, CORPUS_BENCHMARK_MIGRATION_STATEMENTS),
    (CATALOG_RELATIONSHIP_MIGRATION_VERSION, CATALOG_RELATIONSHIP_MIGRATION_STATEMENTS),
    (KNOWLEDGE_RELATIONSHIP_MIGRATION_VERSION, KNOWLEDGE_RELATIONSHIP_MIGRATION_STATEMENTS),
    (CATALOG_ELIGIBILITY_MIGRATION_VERSION, CATALOG_ELIGIBILITY_MIGRATION_STATEMENTS),
    (SEMANTIC_GRAPH_MIGRATION_VERSION, SEMANTIC_GRAPH_MIGRATION_STATEMENTS),
    (CANDIDATE_REGISTRY_MIGRATION_VERSION, CANDIDATE_REGISTRY_MIGRATION_STATEMENTS),
    (
        DOCUMENT_VERSION_CATALOG_MIGRATION_VERSION,
        DOCUMENT_VERSION_CATALOG_MIGRATION_STATEMENTS,
    ),
    (
        SEMANTIC_GRAPH_RESULT_BINDING_MIGRATION_VERSION,
        SEMANTIC_GRAPH_RESULT_BINDING_MIGRATION_STATEMENTS,
    ),
    (
        CORPUS_SYNTHESIS_TASK_MIGRATION_VERSION,
        CORPUS_SYNTHESIS_TASK_MIGRATION_STATEMENTS,
    ),
    (
        INVENTORY_IDENTITY_BINDING_MIGRATION_VERSION,
        INVENTORY_IDENTITY_BINDING_MIGRATION_STATEMENTS,
    ),
)
